### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MinshuG** [wxyn3/wxyn3#3]
![image](https://user-images.githubusercontent.com/65584814/153756769-13b75c67-7053-421b-91d5-cd3ca30c6952.png)

**Comment by localfossa** [comment]
Bruh it is a virus. Dont open the exe.

**Comment by Xbox-360-1063** [comment]
its a virus, dont download it

**Comment by MinshuG** [comment]
But my defender says it is

**Comment by Xbox-360-1063** [comment]
yes, it is a virus
